### PR TITLE
feat(network): Add stabilitytestnet network and FREE currency

### PR DESCRIPTION
**Pull request by deblanco**
## Summary

This PR adds support for [Stability Testnet](https://github.com/stabilityprotocol/) network.

## Changes
* supportedChains
* networks
* Blockchain icon img

## Issues
NA

For further information, please reach the following email: kerk@stabilityprotocol.com

### CODE REVIEW

**Comment by isaackps** [comment]
hi, can fix this CI and update this repo after tt-verfy has been updated, because there is a dependency on tt-verify repo.

**Comment by deblanco** [comment]
> hi, can fix this CI and update this repo after tt-verfy has been updated, because there is a dependency on tt-verify repo.

ready to go, thanks!

**Comment by deblanco** [comment]
@isaackps 

tt-verify PR: https://github.com/TradeTrust/tt-verify/pull/12

We will take care of bumping the dependency once it's merged

**Comment by deblanco** [comment]
@isaackps `tt-verify` dependency updated

**Review by isaackps — APPROVED** [review]

**Pull request merged**
